name: front
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^1.3.0
  flutter_svg: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  google_sign_in: ^6.1.4
  flutter_animate: ^4.2.0
  http: ^1.0.0
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/peace.svg
    - assets/icons/close.svg
    - assets/icons/home.svg
    - assets/icons/helmet.svg
    - assets/icons/chat.svg
    - assets/icons/me.svg
    - assets/icons/edit.svg
    - assets/icons/google.svg
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
