name: front
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  bloc: ^8.1.0
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  flutter_bloc: ^8.0.0
  formz: ^0.6.0
  flutter_svg: ^2.0.5
  flow_builder: ^0.0.9
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/peace.svg
    - assets/icons/close.svg
    - assets/icons/home.svg
    - assets/icons/helmet.svg
    - assets/icons/chat.svg
    - assets/icons/me.svg
    - assets/icons/edit.svg
    - assets/icons/google.svg
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf

dependency_overrides:
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  flutter_bloc: ^8.1.1