name: authentication_repository
description: Dart package for Flutter apps that provides authentication methods using Firebase.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cache:
    path: ../cache
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  google_sign_in: ^6.1.4
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_platform_interface: ^6.15.0
  firebase_core_platform_interface: ^4.8.0
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.4